[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "luseepy"
authors = [{name = "Potekhin", email = "potekhin@bnl.gov"}]
dynamic = ["version", "description"]
